### ISSUE TITLE
Multiple declarations of ...

### ISSUE THREAD

**Issue by jwaldmann** [apunktbau/co4#111]
in the picture hanging example, this function 
```
tails xs = case xs of
  [] -> [[]]
  y:ys -> xs : tails ys
```
gives this error in CO4 compilation
```
test/CO4/Example/Hang.hs:17:4:
    Multiple declarations of ‘encTailsPolyInstance_2969’
    Declared at: test/CO4/Example/Hang.hs:17:4
                 test/CO4/Example/Hang.hs:17:4
```
I think the semantics (as a plain Haskell program) is OK:
```
*CO4.Example.HangStandalone> tails "foobar"
["foobar","oobar","obar","bar","ar","r",""]
```

**Comment by apunktbau** [comment]
> in the picture hanging example, this function gives this error in CO4 compilation

Because `tails` is already defined in CO4's prelude. I fixed `Hang.hs`. I just added `inits` to the prelude as well and changed `Hang.hs` accordingly.

I would like to add `Hang.hs` to CO4's test suite (https://github.com/apunktbau/co4/blob/master/test/CO4/Test.hs) in order to run it while `cabal test`ing. To do so, `Hang.result` must result in value `IO (Maybe a)` and `Hang.hs` may not be a standalone `Main`module (because it needs to be imported from `Test.hs`). Is that ok for you if I change `Hang.hs` accordingly or do you need it to be a standalone module?

**Comment by jwaldmann** [comment]
sure, go ahead with the changes.
